FROM node:22-alpine

# Install pnpm
RUN npm install -g pnpm

WORKDIR /src

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy source code
COPY . .

# Expose port
EXPOSE 4000

CMD ["pnpm", "run", "dev"]
