name: Deploy Backend to DigitalOcean

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.prod.yml'
      - '.github/workflows/cd-backend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Repeat this block for each service (gateway, users, shop, etc.)
      - name: Build and push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./backend/api-gateway # Path to service Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/easyseo-gateway:latest

      - name: Build and push Users API
        uses: docker/build-push-action@v5
        with:
          context: ./backend/users-api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/easyseo-users:latest

      # Add other services here...

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout repository (to get compose file)
        uses: actions/checkout@v4

      - name: Copy compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/opt/easyseo/"

      - name: Execute deployment on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /opt/easyseo
            
            # Login to GHCR (using the PAT stored in secrets)
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Pull new images
            docker compose -f docker-compose.prod.yml pull
            
            # Restart containers (detached)
            docker compose -f docker-compose.prod.yml up -d
            
            # Clean up old images to save disk space
            docker image prune -f