FROM node:20-bullseye-slim

WORKDIR /src

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates openssl libssl1.1 \
	&& rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

COPY . .

EXPOSE 5001

# Generate Prisma client before starting the app
CMD ["sh", "-c", "npx prisma generate && npm run dev"]